verify_signatures: false

PreCommit:
  ALL:
    exclude: &default_excludes
      - "spec/fixtures/**/*"

  RuboCop:
    command: "bin/rubocop"
    enabled: true
    on_warn: fail # Treat all warnings as failures
    exclude:
      - *default_excludes

  TrailingWhitespace:
    enabled: true
    exclude:
      - *default_excludes
